name: Deploy in VPS

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Push Docker Image"]
    types:
      - completed

jobs:
  deploy_latest:
    if: ${{ github.event_name == 'workflow_dispatch' || (github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy latest image to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ vars.DOCKER_USER }}" --password-stdin

            NETWORK_ARGS=""
            if [ -n "${{ vars.DOCKER_NETWORK }}" ]; then
              NETWORK_ARGS="--network ${{ vars.DOCKER_NETWORK }}"
            fi

            docker stop ${{ vars.DOCKER_IMAGE }}-app || true
            docker rm ${{ vars.DOCKER_IMAGE }}-app || true
            docker pull ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:latest

            docker run -d --name '${{ vars.DOCKER_IMAGE }}-app' \
              -p '${{ vars.DOCKER_HOST_PORT }}:5173' \
              --restart unless-stopped \
              $NETWORK_ARGS \
              '${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:latest'
