name: Deploy by Tag (Reusable)

on:
  workflow_call:
    inputs:
      image_tag:
        description: Docker image tag to deploy
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy selected image tag to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            set -e
            echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ vars.DOCKER_USER }}" --password-stdin

            docker stop ${{ vars.DOCKER_CONTAINER }} || true
            docker rm ${{ vars.DOCKER_CONTAINER }} || true
            docker pull ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:${{ inputs.image_tag }}

            docker run -d --name '${{ vars.DOCKER_CONTAINER }}' \
              -p '${{ vars.DOCKER_HOST_PORT }}:5173' \
              --restart unless-stopped \
              '${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:${{ inputs.image_tag }}'
